<?php 
/* generated by Choco ORM
 * docs:
 * Author: Jeferson De Freitas
 * licence:
 */

class Historias extends medical_histories {
	protected $db = 'medical_histories', $name = 'historias', $id_persona = null, $map = ['id_persona'], $num_entities = 1;
}