medical_histories:
    departamentos:
        departamento: 
            type: varchar
            size: 50
            required: true
            fill:
                - Habitación 01
                - Habitación 02
                - Habitación 03
                - Habitación 04
                - Habitación 05
                - Habitación 06
                - Habitación 07
                - Habitación 08
                - Habitación 09
                - Habitación 10