medical_histories:
    egreso:
        id_persona: 
            type: int
            join: personas
            required: true
        id_departamento: 
            type: int
            join: departamentos
            required: true
        descripcion: 
            type: text
            required: true
        creacion: 
            type: date
            required: true