medical_histories:
    egreso:
        id_hospitalizacion: 
            type: int
            join: hospitalizacion
            required: true
        descripcion: 
            type: text
            required: true
        creacion: 
            type: datetime
            required: true