medical_histories:
    egreso:
        id_persona: 
          type: int
          join: personas
          required: true
        descripcion: 
          type: int
          join: personas
          required: true