medical_histories:
    ingreso:
        id_hospitalizacion: 
            type: int
            join: hospitalizacion
            required: true
        descripcion: 
            type: text
            required: true
        creacion: 
            type: date
            required: true
