medical_histories:
    laboratorio:
        id_persona: 
            type: int
            join: personas
            required: true
        id_departamento: 
            type: int
            join: departamentos
            required: true
        descripcion: 
            type: text
            required: true
        orina: 
            type: text
            required: true
        hematologia: 
            type: text
            required: true
        heces: 
            type: text
            required: true
        creacion: 
            type: datetime
            required: true