medical_histories:
    permisos:
        permiso: 
            type: varchar
            size: 7
            required: true
            fill:
                - usuario
                - doctor
                - historias
                - enfermera