medical_histories:
    personas:
        nombres: 
            type: varchar
            size: 50
            required: true
        apellidos: 
            type: varchar
            size: 50
            required: true
        cedula: 
            type: int
            required: true
        nacimiento: 
            type: date
            required: true
        direccion: 
            type: varchar
            size: 128
            required: true
        profesion: 
            type: varchar
            size: 20
            required: true
        Lugar_nacimiento: 
            type: varchar
            size: 30
            required: true
        registro: 
            type: date
            required: true
        id_sexo: 
            type: int
            join: sexo
            required: true
        id_tipo_cedula: 
            type: int
            join: tipo_cedula
            required: true
        id_permiso: 
            type: int
            join: permisos
            required: true